In [64]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.family'] = 'Malgun Gothic'  # Windows의 경우
plt.rcParams['axes.unicode_minus'] = False  # 음수 기호 깨짐 방지

In [65]:
crop = "양파"
df = pd.read_csv(f"../data/{crop}_lag처리.csv", encoding="cp949")

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129501 entries, 0 to 129500
Data columns (total 41 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              129501 non-null  int64
 1   week              129501 non-null  int64
 2   week_start        129501 non-null  object
 3   품종코드              129501 non-null  int64
 4   등급코드              129501 non-null  int64
 5   직팜산지코드            129501 non-null  int64
 6   총거래량(kg)          129501 non-null  float64
 7   일평균기온             129501 non-null  float64
 8   최고기온              129501 non-null  float64
 9   최저기온              129501 non-null  float64
 10  평균상대습도            129501 non-null  float64
 11  강수량(mm)           129501 non-null  float64
 12  1시간최고강수량(mm)      129501 non-null  float64
 13  holiday_flag      129501 non-null  int64
 14  holiday_score     129501 non-null  float64
 15  grow_score        129501 non-null  float64
 16  평균단가(원)           129501 non-null  float64
 17  일평균기온_t-1         129501 non-null  float64
 18  최고기온_t-1          129501 non-null  float64
 19  최저기온_t-1          129501 non-null  float64
 20  평균상대습도_t-1        129501 non-null  float64
 21  강수량(mm)_t-1       129501 non-null  float64
 22  1시간최고강수량(mm)_t-1  129501 non-null  float64
 23  일평균기온_t-2         129501 non-null  float64
 24  최고기온_t-2          129501 non-null  float64
 25  최저기온_t-2          129501 non-null  float64
 26  평균상대습도_t-2        129501 non-null  float64
 27  강수량(mm)_t-2       129501 non-null  float64
 28  1시간최고강수량(mm)_t-2  129501 non-null  float64
 29  일평균기온_t-3         129501 non-null  float64
 30  최고기온_t-3          129501 non-null  float64
 31  최저기온_t-3          129501 non-null  float64
 32  평균상대습도_t-3        129501 non-null  float64
 33  강수량(mm)_t-3       129501 non-null  float64
 34  1시간최고강수량(mm)_t-3  129501 non-null  float64
 35  일평균기온_t-4         129501 non-null  float64
 36  최고기온_t-4          129501 non-null  float64
 37  최저기온_t-4          129501 non-null  float64
 38  평균상대습도_t-4        129501 non-null  float64
 39  강수량(mm)_t-4       129501 non-null  float64
 40  1시간최고강수량(mm)_t-4  129501 non-null  float64
dtypes: float64(34), int64(6), object(1)
memory usage: 40.5+ MB

✅ 결측치 개수:
 year                0
week                0
week_start          0
품종코드                0
등급코드                0
직팜산지코드              0
총거래량(kg)            0
일평균기온               0
최고기온                0
최저기온                0
평균상대습도              0
강수량(mm)             0
1시간최고강수량(mm)        0
holiday_flag        0
holiday_score       0
grow_score          0
평균단가(원)             0
일평균기온_t-1           0
최고기온_t-1            0
최저기온_t-1            0
평균상대습도_t-1          0
강수량(mm)_t-1         0
1시간최고강수량(mm)_t-1    0
일평균기온_t-2           0
최고기온_t-2            0
최저기온_t-2            0
평균상대습도_t-2          0
강수량(mm)_t-2         0
1시간최고강수량(mm)_t-2    0
일평균기온_t-3           0
최고기온_t-3            0
최저기온_t-3            0
평균상대습도_t-3          0
강수량(mm)_t-3         0
1시간최고강수량(mm)_t-3    0
일평균기온_t-4           0
최고기온_t-4            0
최저기온_t-4            0
평균상대습도_t-4          0
강수량(mm)_t-4         0
1시간최고강수량(mm)_t-4    0
dtype: int64
✅ 전체 결측치 합: 0
✅ 중복 행 수: 1

In [68]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

print("🔢 수치형 컬럼:", numerical_cols)
print("🔤 범주형 컬럼:", categorical_cols)

🔢 수치형 컬럼: ['year', 'week', '품종코드', '등급코드', '직팜산지코드', '총거래량(kg)', '일평균기온', '최고기온', '최저기온', '평균상대습도', '강수량(mm)', '1시간최고강수량(mm)', 'holiday_flag', 'holiday_score', 'grow_score', '평균단가(원)', '일평균기온_t-1', '최고기온_t-1', '최저기온_t-1', '평균상대습도_t-1', '강수량(mm)_t-1', '1시간최고강수량(mm)_t-1', '일평균기온_t-2', '최고기온_t-2', '최저기온_t-2', '평균상대습도_t-2', '강수량(mm)_t-2', '1시간최고강수량(mm)_t-2', '일평균기온_t-3', '최고기온_t-3', '최저기온_t-3', '평균상대습도_t-3', '강수량(mm)_t-3', '1시간최고강수량(mm)_t-3', '일평균기온_t-4', '최고기온_t-4', '최저기온_t-4', '평균상대습도_t-4', '강수량(mm)_t-4', '1시간최고강수량(mm)_t-4']
🔤 범주형 컬럼: ['week_start']

In [69]:
import numpy as np
from sklearn.preprocessing import RobustScaler

df_scaled = df.copy()

df_scaled['총거래량(kg)'] = np.log1p(df_scaled['총거래량(kg)'])

target = '평균단가(원)'
exclude_cols = ['year', 'week', '품종코드', '등급코드', '직팜산지코드', target]

numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
scale_cols = [col for col in numerical_cols if col not in exclude_cols]

scaler = RobustScaler()
df_scaled[scale_cols] = scaler.fit_transform(df_scaled[scale_cols])

In [70]:
onehot_cols = ['품종코드', '등급코드', '직팜산지코드']
df_encoded = pd.get_dummies(df_scaled, columns=onehot_cols, dtype=int)

In [71]:
print("🎯 최종 행/열 크기:", df_encoded.shape)
df_encoded.head()

🎯 최종 행/열 크기: (129501, 204)

,year,week,week_start,총거래량(kg),일평균기온,최고기온,최저기온,평균상대습도,강수량(mm),1시간최고강수량(mm),...,직팜산지코드_1159,직팜산지코드_1160,직팜산지코드_1162,직팜산지코드_1163,직팜산지코드_1164,직팜산지코드_1166,직팜산지코드_1167,직팜산지코드_1168,직팜산지코드_1169,직팜산지코드_1170
0,2018,5,2018-01-29,-0.320381,-1.279004,-1.465649,-1.115607,-0.947014,0.007463,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2018,5,2018-01-29,0.658141,-1.446520,-1.496183,-1.398844,-0.742987,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2018,5,2018-01-29,0.033421,-1.335597,-1.549618,-0.994220,-0.447561,0.007463,0.0,...,0,0,0,0,0,0,0,0,0,0
3,2018,5,2018-01-29,0.271997,-1.168081,-1.465649,-0.843931,-1.273692,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2018,5,2018-01-29,-0.127072,-1.300509,-1.587786,-1.075145,-0.384761,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
df_encoded.to_csv(f"../data/{crop}_lag_학습용.csv", index=False, encoding='cp949')

✅ 저장 완료